### ISSUE TITLE
An alias "fileupload" was requested but no service could be found.

### ISSUE THREAD

**Issue by VadimIzmalkov** [zendframework/zend-file#20]
While creating object of Http()
`$receiver = new \Zend\File\Transfer\Adapter\Http();`
get exception Zend\ServiceManager\Exception\ServiceNotFoundException:

> An alias "fileupload" was requested but no service could be found.

seems issue belongs to package [zendframework/zend-validator](https://github.com/zendframework/zend-validator)

**Comment by SorX14** [comment]
Got the same issue

**Comment by yourithielen** [comment]
+1

**Comment by vasconce7os** [comment]
I fixed this problem by updating the version ZendFramework in composer.json from "~2.5.0" to "dev-master".

`{
"repositories": [
    {
        "type": "composer",
        "url": "https://packages.zendframework.com/"
    }
],
        "require": {
            "php": ">=5.5",
            "zendframework/zendframework": "dev-master",
        ... other pakeges here
        }
}
`

**Comment by froschdesign** [comment]
@VadimIzmalkov @SorX14 @yourithielen 
Please update your `zendframework/zend-validator` or `zendframework/zendframework` package.
[The `fileupload` alias is available.](https://github.com/zendframework/zend-validator/blob/master/src/ValidatorPluginManager.php#L112)
